### ISSUE TITLE
Decompile failed: Command failed:

### ISSUE THREAD

**Issue by aryanmmd** [only52607/smali2java#11]
**How do I set the settings (in Windows)?**
![Screenshot 2023-08-31 195359](https://github.com/only52607/smali2java/assets/107447324/ae108979-1d9c-4237-b4eb-660a6b2a9606)

**Comment by only52607** [comment]
In windows `jadx.path` is the path to `jadx.bat` file, for example `D:\Jadx\bin\jadx.bat`. You can download the jadx release [here](https://github.com/skylot/jadx/releases). `jadx.options` can be ignored.

**Comment by aryanmmd** [comment]
It shows me this error 
![2](https://github.com/only52607/smali2java/assets/107447324/297aaf28-c04e-46cd-b807-a4922d2fa00b)

**Comment by aryanmmd** [comment]
Thank you, it worked 💕
