### ISSUE TITLE
Fail to refresh decompiled file opened window upon subsequent decompiling attempts.

### ISSUE THREAD

**Issue by manciuszz** [only52607/smali2java#3]
VSCode seems to have a bug/limitation where `await window.showTextDocument(javaDoc, { preview: false })`? needs a certain amount of time to elapse for it to be able to be refreshed?

This makes the decompiling experience on VSCode with this extension really really bad. I have to open Notepad++ and use it to monitor for file changes to remedy this at the moment. Furthermore, the force-open of decompiled file makes this method really annoying, wish we could disable it via parameters or something :/

Anyways, it would be cool to find a solution for this :)

**Comment by only52607** [comment]
Thanks for your feedback, I tried to fix this issue in version 0.0.4, please check for plugin updates.

**Comment by manciuszz** [comment]
Can confirm that version 0.0.4 has resolved the issue. Good job.
