### ISSUE TITLE
Command resulted in an error

### ISSUE THREAD

**Issue by NowDev** [only52607/smali2java#4]
When i hit decompile i get the following error:

![image](https://user-images.githubusercontent.com/33182389/146207229-6e796e42-f1b6-47f9-b14c-6ecc9f875e6a.png)

i've added the jadx path to my user folder, line from settings.json:
"smali2java.jadxPath": "C:\\Users\\me\\jadx-1.3.0\\bin\\jadx.bat"

Running JDK 1.8.0_202, idk if that helps.

**Comment by only52607** [comment]
Have you tried reinstalling extensions?

**Comment by NowDev** [comment]
fix'd by reinstalling, thx
