### ISSUE TITLE
command 'smali2java.decompileCurrentSmaliToJava' not found

### ISSUE THREAD

**Issue by dmcslt** [only52607/smali2java#5]
vscode版本1.63.2,windows10
试了重装、重启都不行
设置了jadxpath，`"smali2java.jadxPath": "D:\\jadx-1.3.1\\bin\\jadx.bat"`
提示`command 'smali2java.decompileCurrentSmaliToJava' not found`

**Comment by only52607** [comment]
扩展是开启状态吗，试试重新关闭启用

**Comment by dmcslt** [comment]
> 扩展是开启状态吗，试试重新关闭启用

是开启的，禁用再启用还是不行

**Comment by nanshihui** [comment]
same as me

**Comment by Think-Jumper** [comment]
The same as me.

**Comment by nanshihui** [comment]
已经收到哦，我会尽快回复你。I have received your email and will reply to you ASAP. Thanks
